name: Deploy Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy files to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          mkdir -p ~/backup
          cp -r ~/httpdocs/* ~/backup/ 2>/dev/null || true
          rm -rf ~/httpdocs/*
          git clone https://github.com/${{ github.repository }}.git ~/pagespeed-impact
          cp -r ~/pagespeed-impact/public/* ~/httpdocs/
          ln -s ~/shared/matomo.js ~/httpdocs/matomo.js
          chown -R ${{ secrets.USERNAME }} ~/httpdocs/
          chmod -R 644 ~/httpdocs/*
          find ~/httpdocs/* -type d -exec chmod 755 {} +
          rm -rf ~/pagespeed-impact
